name: Setup
description: Node setup, install, and build

inputs:
  git_email:
    description: Git email
    required: true
  git_username:
    description: Git author name
    required: true
  node_version:
    description: Node.js version
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        registry-url: https://registry.npmjs.org
        cache: npm

    - name: Configure git user
      shell: bash
      run: |
        git config --global user.email "${{ inputs.git_email }}"
        git config --global user.name "${{ inputs.git_username }}"

    - name: Install npm packages
      shell: bash
      run: npm ci --ignore-scripts

    - name: Build typescript
      shell: bash
      run: npm run build
