name: 'Release'

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        type: choice
        default: 'patch'
        options:
          - 'patch' # bug fixes
          - 'minor' # new features, backwards compatible
          - 'major' # breaking changes

# prevent concurrent releases
concurrency:
  group: npm-release
  cancel-in-progress: true

jobs:
  version-and-release:
    name: Release to NPM
    runs-on: ubuntu-latest

    outputs:
      tagName: ${{ steps.npm-release.outputs.release_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          git_email: clients@pinecone.io
          git_username: ${{ github.actor }}
          node_version: 20.x

      - name: Version and publish to npm
        id: npm-release
        uses: ./.github/actions/npm-release
        with:
          npm_token: ${{ secrets.NPM_TOKEN }}
          release_type: ${{ github.event.inputs.release_type }}

      - run: echo "${{ steps.npm-release.outputs.release_tag }} was published"
