name: 'npm release'
description: 'Publish code changes to npmjs.org'

inputs:
  npm_token:
    description: 'npm token for publishing. Login to npmjs.org to generate this.'
    required: true
  release_type:
    description: 'The semver release type to perform [major, minor, patch]'
    required: true

outputs:
  release_tag:
    description: 'The name of the created git tag'
    value: ${{ steps.release-tag-step.outputs.release-tag }}

runs:
  using: 'composite'
  steps:
    - name: 'Bump version'
      shell: bash
      run: npm version ${{ inputs.release_type }} -m "Publish release %s"

    - name: 'Output release tag'
      shell: bash
      id: release-tag-step
      run: echo "release-tag=$(git describe --tags)" >> $GITHUB_OUTPUT

    - name: 'Publish to npm'
      run: npm publish
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm_token }}

    - name: 'Push changes'
      shell: bash
      run: git push --follow-tags
